/*#############################################################################################
#  ----   UnityVideoPlayerRT   ----
# source of: --> RenderTexture (B8G8R8A8_UNORM)
#
# --------------------------------------------------------------------------------------------
#           $$$$$ IMPORTANT $$$$$$
# In the ITHACA VideoClip you'd like to playback, the sRGB (Color Texture) must be unchecked. If it's checked a gamma correction is applied and deform the depth input.
# Also a Warning we'll indicate you the problem.

# - add Unity video player to the VIdeo Player input

# AND  
# LIGHTSHAFT PART NOT COMPATIBLE !!! Lightshaft you tube is not working properly and Unity Video player doesn't read HSL video format
#then, to use LightShaft (for youtube live streaming capability) :
# - install LigthShaft's Youtube Video Player + Youtube API :
# https://assetstore.unity.com/packages/tools/video/youtube-video-player-youtube-api-29704
# - define the symbol USINGLIGHTSHAFT (go to Project settings > Other Settings > Script compilation
# and add a Scrpting Define Symbol in the list with name USINGLIGHTSHAFT.
# - add a YoutubePlayerLivestream component on your Unity Video Player
#
# (note <lightShaft's Youtube Video Player asset is not free and must be purchased)
#
# --------------------------------------------------------------------------------------------
# Project: IthacaEmetteurRecepteur by FrenchTouchFactory
# Resp. : François
# Author(s): 
# François Bouille (f.bouille@frenchtouchfactory.com), inspired by AVProReceptorRT
# # Starting date : 2024/06/25
# Latest version date : created on 2024/11/26
# Problem : For the moment we have been working with AVpro 2 player, which is really pratical and adaptable to any device. But this plugin is not free, more over a new version AVpro 3 has been released. Some users won't want to use it. 
# Hypothesis : It's possible to generate a Render Texture from a Unity Video Player reading a Video Clip generated by ITHACA.
# Description : Inspired by the AVproReceptorRT, Everytime a generated texture has a different frame count from the latest we generate a new Output. 
# Limits : Only works with built in video clips
# Further improvements : 
# 
# Parameters : 
# Note : Changes made in order to be able to instantiate the receptor from script and pass it a reference of the video player.
# Compute shader needed : No compute shader needed
# Tests : Tested on 4 cams MP4, To be tested on a full 8 cam character and on Android/VR/AR headsets
#############################################################################################*/


using System;
using UnityEngine;
//using UnityEngine.Experimental.Rendering;
//using UnityEngine;
using UnityEngine.Video;

namespace IthacaLib
{
    /// <summary>
    /// Module for handling a Unity Video Player. As a source of RenderTexture it sends streams of events with Unity RenderTexture each time a new frame arrives from the Unitry Video Player.
    /// </summary>
    public class UnityVideoPlayerRT : SourceModuleBase<RenderTexture>
    {
        public override event EventHandler<DataEventArgs<RenderTexture>> OutputReady;
        public override event EventHandler HotInitialized;


        [Header("This module is a RenderTexture source")]
        [Tooltip("There must be a Unity Video Player in your project. It should find it automatically on Play, otherwise please put it here.")]
        [SerializeField] VideoPlayer _videoPlayer;

        public VideoPlayer VideoPlayer { get { return _videoPlayer; } set { _videoPlayer = value; } }
        // To use Youtube Live Streams, install LightShaft :
        /*#if USINGLIGHTSHAFT
                [Tooltip("URL of a youtube live channel Ex: \"https://www.youtube.com/watch?v=wUz1Vb7I2DU\" ")]
                public string youtubeLiveURL = "https://www.youtube.com/watch?v=LpoyHAwT7mE"; // Nautilus Live | Channel 2 Stream for test
        #endif*/
        [Tooltip("If Unity Video Player doesn't provide a Texture in this target resolution, a resampling will occur.")]
        [SerializeField]
        private Vector2Int targetResolution = new Vector2Int(1280, 720);

        public Vector2Int TargetResolution
        {
            get { return targetResolution; }
            set { targetResolution = value; hotInitialized = false; }
        }

        [Tooltip("Pass this to true if you wish to force the resolution of the renderTextures obtained from Unity Video Player to the values specified in targetResolution. Otherwise the resolution of the RT obtained from the media player will be used")]
        public bool ForceTargetResolution = false;

        [Tooltip("Vertically flips the image. DO NOT CHANGE unless you know what you're doing : Exposed here for clarity but this setting is set depending on the system (Windows:false, Android:true)")]
        [SerializeField]

        private bool flipRenderTexture = false; //no Android or Desktop different cases because the Unity video player flip automatically the video when playing (different from AVpro)

        private Vector2 scaleRT = new Vector2(1, 1);
        private Vector2 offsetRT = new Vector2(0, 0);



        private int currentFrameID;
        private RenderTexture currentRT;
        private RenderTexture currentRT1;
        private RenderTexture currentRT2;
        private bool useCurrentRT2 = false;
        bool hotInitialized = false;
        private int lastFrame = 0; // Number of the last Texture frame, for launching new Texture2DReady event
        private int producedFrameCount = 0;

        //DEBUG STUFFS
        [Tooltip("Resolution of the Texture given by Unity Video Player at each frame.")]
        public Vector2Int debugTextureRes = Vector2Int.zero;
        private RenderTextureReadWrite rtReadWriteFormat;

        #region Unity framework logic

        private void Start()
        {
            Connect();
        }
        public void Connect()
        {
            if (_videoPlayer == null) _videoPlayer = GetComponent<VideoPlayer>();
/*#if USINGLIGHTSHAFT
                        if (youtubeLiveURL != null) _videoPlayer.GetComponent<YoutubePlayerLivestream>()._livestreamUrl = youtubeLiveURL;
#endif*/
            if (_videoPlayer == null)
            {
                Debug.Log("The video player is not set");
                return;
            }
            _videoPlayer.prepareCompleted += OnVideoReady;
            _videoPlayer.loopPointReached += OnLoopPointReached;
            _videoPlayer.frameDropped += OnFrameDropped;

        }
        public void Disconnect()
        {
            if (_videoPlayer == null) _videoPlayer = GetComponent<VideoPlayer>();

            if (_videoPlayer == null)
            {
                Debug.Log("The video player is not set");
                return;
            }
            _videoPlayer.prepareCompleted -= OnVideoReady;
            _videoPlayer.loopPointReached -= OnLoopPointReached;
            _videoPlayer.frameDropped -= OnFrameDropped;

        }
        void OnValidate()
        {
            if (_videoPlayer == null) _videoPlayer = GetComponent<VideoPlayer>();
/*#if USINGLIGHTSHAFT
                        if (youtubeLiveURL != null) _videoPlayer.GetComponent<YoutubePlayerLivestream>()._livestreamUrl = youtubeLiveURL;
#endif*/
            hotInitialized = false;
        }

        public void Update()
        {
            if (!enabled || _videoPlayer == null || _videoPlayer.texture == null)// useful for the case of editor scrubing being on but the pipeline not being enabled
            {
                return;
            }
            if (lastFrame != (int)_videoPlayer.frame)
            {
                if (!hotInitialized) HotInit(_videoPlayer.texture); //ERREUR RARE : il arrive qu'on n'ait pas de Texture ici (du coup le debug.log dans l'initialise ne marche pas)

                currentFrameID = (int)_videoPlayer.frame;

                if (OutputReady != null)
                {   //If no one listen for a RT, we do no blit and no invoke
                    producedFrameCount += 1;
                    FrameInfo frameInfo = new(0, producedFrameCount, (long)(_videoPlayer.time * 1000000)); // the timestamp is in microseconds but the time of videoPlayer is expressed in seconds

                    Graphics.Blit(_videoPlayer.texture, currentRT, scaleRT, offsetRT);  //... so we do a blit for the conversion into a RenderTexture and for 
                                                                                        //OutputReady?.Invoke(this, new DataEventArgs<RenderTexture>(currentRT, currentFrameID));  // its "magic" resizing property (if needed)
                    OutputReady?.Invoke(this, new DataEventArgs<RenderTexture>(currentRT, frameInfo));

                }

                lastFrame = (int)_videoPlayer.frame;

                //DEBUGS
                if (_videoPlayer.texture != null)
                {
                    debugTextureRes = new Vector2Int(_videoPlayer.texture.width, _videoPlayer.texture.height);
                }
            }
        }

        protected override void OnDestroy()
        {
            Disconnect();
            base.OnDestroy();
            // Release RenderTextures
            currentRT = null;
            RenderTexture.ReleaseTemporary(currentRT1);
            RenderTexture.ReleaseTemporary(currentRT2);
        }
        #endregion

        ///<summary>Creates or recreates the RenderTexture, sets some parameters.</summary>
        void HotInit(Texture UnityVideoTexture)
        {
            if (UnityVideoTexture == null) { return; }
            //Just import the video in the assets and let the sRGB activated, the gamma is corrected when declaring the RT
            /*if (_videoPlayer.clip !=null)
            { 
                if (_videoPlayer.clip.sRGB == true) Debug.Log("Warning !!! The VideoClip Format used is sRGB : " + _videoPlayer.clip.sRGB + ", Please uncheck sRGB and apply to the video clip so that ITHACA can decode the depth properly."); 
            }*/


            scaleRT =  new Vector2(1, 1); // no need for different cases as unity video player flips the texture when needed 
            offsetRT = new Vector2(0, 0);

            if (!ForceTargetResolution)
            {
                targetResolution.Set(UnityVideoTexture.width, UnityVideoTexture.height);
            }

            //Only way I found to follow up the color space of the video clip
            if (_videoPlayer.source == VideoSource.VideoClip && _videoPlayer.clip != null)
            {
                if (_videoPlayer.clip.sRGB)
                    rtReadWriteFormat = RenderTextureReadWrite.sRGB;
                else
                    rtReadWriteFormat = RenderTextureReadWrite.Linear;
            }

            else if (_videoPlayer.source == VideoSource.Url && _videoPlayer.url != null)
            {
                rtReadWriteFormat = RenderTextureReadWrite.sRGB;
            }
            Debug.Log("RenderTextureReadWrite Format : " + rtReadWriteFormat);
            // //currentRT.memorylessMode = RenderTextureMemoryless.Color; // Very very touchy stuuf, need to be investigated... could speed up things on mobiles, maybe...


            // WIP: this is a double RT system designed to get rid of error "Setting width of already created render texture is not supported!"
            // but it just corrects the error "CopyTexture called with mismatching texture sizes". Well it's working, but it seems dirty.
            // The important stuff here is to understand how to get rid of a RenderTexture in memory in a clean way.


            if (!useCurrentRT2)
            {
                if (currentRT2 != null) RenderTexture.ReleaseTemporary(currentRT2);
                //currentRT1 = RenderTexture.GetTemporary(targetResolution.x, targetResolution.y, 0, UnityVideoTexture.graphicsFormat);
                currentRT1 = RenderTexture.GetTemporary(targetResolution.x, targetResolution.y, 0, RenderTextureFormat.BGRA32, rtReadWriteFormat);
                currentRT = currentRT1;
            }
            else
            {
                if (currentRT1 != null) RenderTexture.ReleaseTemporary(currentRT1);
                //currentRT2 = RenderTexture.GetTemporary(targetResolution.x, targetResolution.y, 0, UnityVideoTexture.graphicsFormat);
                currentRT2 = RenderTexture.GetTemporary(targetResolution.x, targetResolution.y, 0, RenderTextureFormat.BGRA32, rtReadWriteFormat);
                currentRT = currentRT2;
            }
            Debug.Log("UnityVideoPlayerRT: Initializing currentRT with graphicsFormat " + currentRT.graphicsFormat + ", Rez: " + targetResolution.x + ", " + targetResolution.y);
            //currentRT = RenderTexture.GetTemporary(targetResolution.x, targetResolution.y, 0, RenderTextureFormat.BGRA32, RenderTextureReadWrite.Linear);
            currentRT.filterMode = FilterMode.Point;

            HotInitialized?.Invoke(this, EventArgs.Empty);
            if (_videoPlayer != null) //useless for the moment
            {
                //Q:: our script will listen to all of the events launched by the mediaPlayer and pass it to OnMediaPlayerEvent for treatment
                //_videoPlayer.
                //_videoPlayer.Events.AddListener(OnMediaPlayerEvent);
            }
            //_mediaPlayer.UseResampler = false;
            hotInitialized = true;
            Debug.Log("hotInitialized = " + hotInitialized);
        }


        ///<summary>Returns true when app is playing and a mediaPlayer and TextureProducer exists and the GetTexture() returns something.</summary>
		public bool HasValidTexture()
        {
            return (Application.isPlaying && _videoPlayer != null && _videoPlayer.texture != null);
        }

        // Callback function to handle Unity Video Player events


        void OnVideoReady(VideoPlayer readyPlayer)
        {
            //readyPlayer.Play();
            Debug.Log("Unity Video Player event: FirstFrameReady - TextureFrame = " + _videoPlayer.frame);
        }

        void OnLoopPointReached(VideoPlayer readyPlayer)
        {

            Debug.Log("Unity Video Player event: Loop Point Reached - TextureFrameCount = " + _videoPlayer.frameCount);
        }

        void OnFrameDropped(VideoPlayer readyPlayer)
        {

            Debug.Log("Unity Video Player event: Frame Dropped - TextureFrame number = " + _videoPlayer.frame);
        }


        /// <summary>
		/// Returns the current (Unity) Texture produced by Unity Video Player if needed outside the event system.
		/// </summary>
		public Texture mainTexture
        {
            get
            {
                Texture result = Texture2D.whiteTexture;
                if (HasValidTexture())
                    result = _videoPlayer.texture;
                else
                    result = null;

                return result;
            }
        }
    }
}

