/*#############################################################################################
# ---- PosColMapCombinatorForPerspectiveFusion_android ----
# Project: IthacaEmetteurRecepteur by FrenchTouchFactory
# Resp. : François
# Author(s): François Bouille (f.bouille@frenchtouchfactory.com)
# Starting date : 2024/04/04
# Latest version date : created on 2025/02/23
# Problem : Isometric or orthogonal fusion induces a displaying issue with a perspective camera. The perspective sees unwanted datas and hide datas generated by the isometric fusion. 
# Hypothesis : Cubic ortho fusion is usefull to store fused data and export it with a good resolution, but is not perfect for display as exposed. Developping a perspective fusion can solve this issue.  
# Description: V1.0 : Solves the perspective problem when displaying a projected planar mesh. From several Tuple Position & Color we project each point of the point cloud on the front face of a cube following the orientation of the main camera. The point on this plane is defined by the intersection of
# the line (point-camera position) and the plane. The datas are fused like we already did in the ortho fusion. To compensate the density issues appearing when the camera get closer to the character
# we apply a damping function and reduce the size of the cube (consequently the plane), we also added the option not to fuse the cameras located at more than 90° from the display camera for optimisation purposes.
# In the compute shader the comparator was modified from != 0 to >0.01 brcause from some reason the very small values are interpreted as 0 values.
# We added a "fusion" boolean to activate the fusion between 2 close surfaces.
# V1.0 Limits : The zone where the density is weak can generate holes when projected on the plane or project unwanted sides of the character. Edges of the character can appear blury or flickery. 
# Further improvements :  V1.0 Need to be tested on denser point clouds (Depth to Color), work on developing a optimized fusion algorithms in the next version.
# V2.0 : Added rasterization to solve density problems and separate the process of perspective fusion in 2 steps (preparation and fusion)
# V2.0 Limits : The perspective projection with triangle rasterization generates now too much data from time to time above all on auto occluded zone by linking two vertices far from eachother
# V2.0 The rasterization might be fastened with a more optimized triangle filling method according to the rasterization rules 
# Parameters : PosColMap sources list, PosColMapToFuse, FinalWidth, FinalHeight, FinalDepth, Bounding Box, Depth fusion distance, Fusion Display, camera, scalar angle limit, voxelize switch (not finished) because it's linked to the export and could not be necessary, damping power, occlude opposite cameras.
# Note : Need edge filter and weighted poscolmaps
# V2.1 Damping method abandonned to the profit of a fixed projection surface attached to the camera => Creation of a virtual kinect
# Compute shader needed : V2.0 PerspectiveFusionTrisDensifierCompute and PerspectiveFusionCompute_prepared
# V2.2 Added the Temporal Anti Aliasing Processing to suppress the edges jittering and be able to turn around the hologram with the camera real time
# Added a motion detection to constraint the temporal noise removal to slow motion
# Suppressed the possibility to fuse the holograms in the preparation to perspective fusion
# V2.3 More robust and optimized triangle ratesrization (based on scanline and DDA algorithms) - Also made it compatible with ANDROID
# Tests : Tested on 5 cams MP4, Double buffer added for MKV and direct live sensors, To be tested on a full 9 cam character
#############################################################################################*/

using System;
using System.Linq;
using UnityEngine;
using System.IO;

namespace IthacaLib
{

    ///<Summary>It produces a Fused PosColMap with Depth and Color images from several filtered and Weighted PosColMaps. Iso projection of the PC datas on the Final Depth and Color. 
    ///The final PosColMap is defined proportionnaly by the front side of the bounding box, the FinalWidth and the FinalHeight. For a perfect result the FinalPosColMap data alpha channel should be defined at 1 after fusion in the future.
    ///But it already works with an alpha > 0 cos the display method we use in shader and VFX graph only takes the alpha = 0 or alpha >0 into account</summary>
    //public class PosColMapCombinatorForPerspectiveFusion : SourceModuleBase<Queue<GPUPointCloud>>
    public class PosColMapCombinatorForPerspectiveFusion_android : PosColMapCombinatorForPerspectiveFusion
    {  
        private RenderTexture PosMapIntermediate;
        private RenderTexture ColMapIntermediate;
        public override void HotInit()
        {
            PrepareIntermediatePositionBuffer();
            PrepareIntermediateColorBuffer();
            base.HotInit();
        }

        private void PrepareIntermediatePositionBuffer()
        {
            PosMapIntermediate = new RenderTexture(finalWidth, finalHeight, 0, RenderTextureFormat.ARGBFloat)
            {
                enableRandomWrite = true,
                useMipMap = false,
                filterMode = FilterMode.Point,
                name = "perspPosIntermediate"
            };
            PosMapIntermediate.Create();

        }

        private void PrepareIntermediateColorBuffer()
        {
            ColMapIntermediate = new RenderTexture(finalWidth, finalHeight, 0, RenderTextureFormat.ARGB32) 
            {
                graphicsFormat = UnityEngine.Experimental.Rendering.GraphicsFormat.R8G8B8A8_UNorm,
                enableRandomWrite = true,
                useMipMap = false,
                filterMode = FilterMode.Point,
                name = "perspColIntermediate"
            };
            ColMapIntermediate.Create();

        }

        class ID_android : ID
        {


            public static int PosMapIntermediate = Shader.PropertyToID("PosMapIntermediate");
            public static int ColMapIntermediate = Shader.PropertyToID("ColMapIntermediate");

            
        }


        protected override void PerspFusionDataProcess(GPUPointCloud PCin)
        {
            RenderTexture colorsOut, positionsOut;

            if (!usePairBuffer)
            {
                colorsOut = colorsOut1;
                positionsOut = positionsOut1;
            }
            else
            {
                colorsOut = colorsOut2;
                positionsOut = positionsOut2;
            }
            //Debug.Log("Fusion Done ? : " + fusionDone);
            if (fusionDone)//||fusion==false
            {
                //Graphics.SetRenderTarget(colorsOut);
                //Clear the out Rendertextures Buffers at each initialization of a new fusion
                RenderTexture.active = colorsOut;
                GL.Clear(true, true, Color.clear);
                RenderTexture.active = positionsOut;
                GL.Clear(true, true, Color.clear);
                RenderTexture.active = depthMap;
                GL.Clear(true, true, Color.clear);

                RenderTexture.active = PosMapIntermediate;
                GL.Clear(true, true, Color.clear);
                RenderTexture.active = ColMapIntermediate;
                GL.Clear(true, true, Color.clear);

                //Once by fusion cycle prepare the array of component to be fused. Only the kinects in the same axis than the main camera are fused.
                if (occludeOppositeCameras)
                {
                    PreparePosColMapToFuse();
                    allCamsToFuse = false;
                }
                else if (!occludeOppositeCameras && !allCamsToFuse)
                {
                    AddAllCamstoFusion();
                    allCamsToFuse = true;
                }
            }


            //Fusion parameters
            PerspFusionCompute.SetTexture(kernelIndex, ID.ColMapOut, colorsOut);
            PerspFusionCompute.SetTexture(kernelIndex, ID.PosMapOut, positionsOut);
            PerspFusionCompute.SetTexture(kernelIndex, ID.DepthMap, depthMap);

            PerspFusionCompute.SetTexture(kernelIndex, ID_android.ColMapIntermediate, ColMapIntermediate);
            PerspFusionCompute.SetTexture(kernelIndex, ID_android.PosMapIntermediate, PosMapIntermediate);

            //OrthoFusionCompute.SetBool(ID.startNewFusion, fusionDone);
            //PerspFusionCompute.SetBool(ID.voxelized, voxelize);
            PrepareAdaptativeProjection();
            PerspFusionCompute.SetVector(ID.O, Origin);
            PerspFusionCompute.SetVector(ID.X, Xcorner);
            PerspFusionCompute.SetVector(ID.Y, Ycorner);
            PerspFusionCompute.SetVector(ID.Z, Zcorner);
            //PerspFusionCompute.SetVector(ID.bBoxPivot, BoundingBoxPivot);

            // send the world position of the cam in the vector 4
            //Debug.Log("camera position : " + cam.transform.TransformPoint(new Vector4(cam.transform.localPosition.x, cam.transform.localPosition.y, cam.transform.localPosition.z, 0)));

            //PerspFusionCompute.SetVector(ID.camPos, cam.transform.TransformPoint(new Vector4(cam.transform.localPosition.x, cam.transform.localPosition.y, cam.transform.localPosition.z, 0)));
            //Debug.Log("camera position : " + new Vector4(cam.transform.position.x, cam.transform.position.y, cam.transform.position.z, 0));
            PerspFusionCompute.SetVector(ID.camPos, new Vector4(cam.transform.position.x, cam.transform.position.y, cam.transform.position.z, 0));

            PerspFusionCompute.SetInt(ID.orthoWidth, finalWidth);
            PerspFusionCompute.SetInt(ID.orthoHeight, finalHeight);
            PerspFusionCompute.SetInt(ID.orthoDepth, finalDepth);
            PerspFusionCompute.SetFloat(ID.depthThrsld, depthThreshold_Z_meter);
            PerspFusionCompute.SetInt(ID.Thickness, thickness);
            PerspFusionCompute.SetFloat(ID.scalarNormalLimit, scalarAngleLimit);
            PerspFusionCompute.SetMatrix(ID.bBoxMat, bBoxMatrix);
            PerspFusionCompute.SetBool(ID.FlipNormalsComparator, flipNormalsComparator);
            PerspFusionCompute.SetBool(ID.Fusion, fusion);
            //PerspFusionCompute.SetInt(ID.DebugPixelWidth, debugPixelWidth);
            //PerspFusionCompute.SetInt(ID.DebugPixelHeight, debugPixelHeight);

            // Add current frame to buffer and remove oldest if necessary
            //frameBuffer.Enqueue(new GPUPointCloud(PCin));
            //if (frameBuffer.Count > maxFrameHistory)
            //{
            //    var oldFrame = frameBuffer.Dequeue();
            //    oldFrame.Dispose();
            //}

            //int frameIndex = 0;
            //foreach (var frame in frameBuffer)
            //{
            // 
            //    {
            //        PerspFusionCompute.SetTexture(kernelIndex, ID.PosMapRead, frame.positionMap);

            //        PerspFusionCompute.SetTexture(kernelIndex, ID.ColMapRead, frame.colorMap);

            //        PerspFusionCompute.Dispatch(kernelIndex, threadGroupsX, threadGroupsY, threadGroupsZ);
            //    }

            //    frameIndex++;
            //}

            if (TaaActivated && !fusion) // Can only be used in the preparation to fusion
            {
                if (historyCleared) historyCleared = false;
                //TAA parameters
                TemporalNoiseRemoverCompute.SetInt(ID.TaaDelay, TaaDelay);
                TemporalNoiseRemoverCompute.SetInt(ID.TaaThickness, TaaThickness);
                TemporalNoiseRemoverCompute.SetFloat(ID.TaaDepthThreshold, TaaDepthThreshold);
                TemporalNoiseRemoverCompute.SetBool(ID.TaaVisualize, TaaVisualize);

                TemporalNoiseRemoverCompute.SetFloat(ID.motionThreshold, motionThreshold);
                TemporalNoiseRemoverCompute.SetBool(ID.motionVisualize, motionVisualize);

                if (TaaCurrentDelay != TaaDelay) HotInit();

                // Add current frame to buffer and remove oldest if necessary
                frameBuffer.Enqueue(new GPUPointCloud(PCin));

                while (frameBuffer.Count > TaaDelay * 2 + 1)
                {
                    var oldFrame = frameBuffer.Dequeue();
                    oldFrame.Dispose();
                }

                // Set previous frames in the compute shader

                int frameIndex = 0;
                foreach (var frame in frameBuffer)
                {

                    //PosMap Read
                    PerspFusionCompute.SetTexture(kernelIndex, ID.PosMapRead, frame.positionMap);
                    //ColMap Read
                    PerspFusionCompute.SetTexture(kernelIndex, ID.ColMapRead, frame.colorMap);

                    PerspFusionCompute.Dispatch(kernelIndex, threadGroupsX, threadGroupsY, threadGroupsZ);

                    Graphics.CopyTexture(positionsOut, 0, 0, positionHistory, frameIndex, 0);
                    Graphics.CopyTexture(colorsOut, 0, 0, colorHistory, frameIndex, 0);

                    RenderTexture.active = colorsOut;
                    GL.Clear(true, true, Color.clear);
                    RenderTexture.active = positionsOut;
                    GL.Clear(true, true, Color.clear);
                    RenderTexture.active = depthMap;
                    GL.Clear(true, true, Color.clear);



                    frameIndex++;

                }
                //Test de vizualisation de la frame Delay après traitement par la persp fusion
                //Graphics.CopyTexture(positionHistory, TaaDelay, 0,positionsOut, 0, 0);
                //Graphics.CopyTexture(colorHistory, TaaDelay, 0,colorsOut, 0, 0);

                TemporalNoiseRemoverCompute.SetTexture(kernelIndex2, ID.ColMapOut, colorsOut);
                TemporalNoiseRemoverCompute.SetTexture(kernelIndex2, ID.PosMapOut, positionsOut);

                TemporalNoiseRemoverCompute.SetTexture(kernelIndex2, ID.PositionHistory, positionHistory);
                TemporalNoiseRemoverCompute.SetTexture(kernelIndex2, ID.ColorHistory, colorHistory);
                TemporalNoiseRemoverCompute.Dispatch(kernelIndex2, threadGroupsX2, threadGroupsY2, threadGroupsZ2);
            }
            else
            {
                if (!historyCleared)
                {
                    frameBuffer.Clear();
                    RenderTexture.active = positionHistory;
                    GL.Clear(true, true, Color.clear);
                    RenderTexture.active = colorHistory;
                    GL.Clear(true, true, Color.clear);
                    historyCleared = true;
                }

                PerspFusionCompute.SetTexture(kernelIndex, ID.PosMapRead, PCin.positionMap);

                PerspFusionCompute.SetTexture(kernelIndex, ID.ColMapRead, PCin.colorMap);
                PerspFusionCompute.Dispatch(kernelIndex, threadGroupsX, threadGroupsY, threadGroupsZ);

                RenderTexture.active = PosMapIntermediate;
                GL.Clear(true, true, Color.clear);
                RenderTexture.active = ColMapIntermediate;
                GL.Clear(true, true, Color.clear);
                Graphics.CopyTexture(positionsOut, 0, 0, PosMapIntermediate, 0, 0);
                Graphics.CopyTexture(colorsOut, 0, 0, ColMapIntermediate, 0, 0);



            }
            if (fusionDone) fusionDone = false;
        }

        public override void CleanUp()
        {
            base.CleanUp();
            Destroy(PosMapIntermediate);
            Destroy(ColMapIntermediate);
        }
    }
}