/*#############################################################################################
# ---- PosColMapCombinatorForPerspectiveFusion ----
# Project: IthacaEmetteurRecepteur by FrenchTouchFactory
# Resp. : François
# Author(s): François Bouille (f.bouille@frenchtouchfactory.com)
# Starting date : 2024/04/04
# Latest version date : created on 2024/12/09
# Problem : Isometric or orthogonal fusion induces a displaying issue with a perspective camera. The perspective sees unwanted datas and hide datas generated by the isometric fusion. 
# Hypothesis : Cubic ortho fusion is usefull to store fused data and export it with a good resolution, but is not perfect for display as exposed. Developping a perspective fusion can solve this issue.  
# Description: V1.0 : Solves the perspective problem when displaying a projected planar mesh. From several Tuple Position & Color we project each point of the point cloud on the front face of a cube following the orientation of the main camera. The point on this plane is defined by the intersection of
# the line (point-camera position) and the plane. The datas are fused like we already did in the ortho fusion. To compensate the density issues appearing when the camera get closer to the character
# we apply a damping function and reduce the size of the cube (consequently the plane), we also added the option not to fuse the cameras located at more than 90° from the display camera for optimisation purposes.
# In the compute shader the comparator was modified from != 0 to >0.01 brcause from some reason the very small values are interpreted as 0 values.
# We added a "fusion" boolean to activate the fusion between 2 close surfaces.
# V1.0 Limits : The zone where the density is weak can generate holes when projected on the plane or project unwanted sides of the character. Edges of the character can appear blury or flickery. 
# Further improvements :  V1.0 Need to be tested on denser point clouds (Depth to Color), work on developing a optimized fusion algorithms in the next version.
# V2.0 : Added rasterization to solve density problems and separate the process of perspective fusion in 2 steps (preparation and fusion)
# V2.0 Limits : The perspective projection with triangle rasterization generates now too much data from time to time above all on auto occluded zone by linking two vertices far from eachother
# V2.0 The rasterization might be fastened with a more optimized triangle filling method according to the rasterization rules 
# Parameters : PosColMap sources list, PosColMapToFuse, FinalWidth, FinalHeight, FinalDepth, Bounding Box, Depth fusion distance, Fusion Display, camera, scalar angle limit, voxelize switch (not finished) because it's linked to the export and could not be necessary, damping power, occlude opposite cameras.
# Note : Need edge filter and weighted poscolmaps
# V2.1 Damping method abandonned to the profit of a fixed projection surface attached to the camera => Creation of a virtual kinect
# Compute shader needed : V2.0 PerspectiveFusionTrisDensifierCompute and PerspectiveFusionCompute_prepared
# V2.2 Added the Temporal Anti Aliasing Processing to suppress the edges jittering and be able to turn around the hologram with the camera real time
# Tests : Tested on 5 cams MP4, Double buffer added for MKV and direct live sensors, To be tested on a full 9 cam character
#############################################################################################*/

using System;
using System.Linq;
using UnityEngine;

//using K4AdotNet.Sensor;
using IthacaLib.Common;
using System.Collections.Generic;
using System.IO;

namespace IthacaLib
{

    ///<Summary>It produces a Fused PosColMap with Depth and Color images from several filtered and Weighted PosColMaps. Iso projection of the PC datas on the Final Depth and Color. 
    ///The final PosColMap is defined proportionnaly by the front side of the bounding box, the FinalWidth and the FinalHeight. For a perfect result the FinalPosColMap data alpha channel should be defined at 1 after fusion in the future.
    ///But it already works with an alpha > 0 cos the display method we use in shader and VFX graph only takes the alpha = 0 or alpha >0 into account</summary>
    //public class PosColMapCombinatorForPerspectiveFusion : SourceModuleBase<Queue<GPUPointCloud>>
    public class PosColMapCombinatorForPerspectiveFusion : SourceModuleBase<GPUPointCloud>
    {
        [Tooltip("PerspectiveFusionCompute is the choice")]
        public ComputeShader PerspFusionCompute;
        protected RenderTexture positionsOut1;
        protected RenderTexture positionsOut2;
        protected RenderTexture colorsOut1;
        protected RenderTexture colorsOut2;

        protected RenderTexture depthMap; //Z buffer

        protected VideoResolution containerRes;


        protected int[] posColMapFrameID;
        public bool fusion;
        [Tooltip("A source of colMap Image, i.e. a IImageProducer. Will automatically plug to a ColorToDepthTransformer nearby for convenience, but it can be changed of course.")]
        public Component[] posColMapSources;
        //public Component[] posColMapToFuse;
        public List<Component> posColMapToFuse = new List<Component>();

        [Tooltip("Resolution of the Final Ortho Fusionned PosColMap, cannot the more dense than the point clouds")]
        public int finalWidth;
        public int finalHeight;
        public int finalDepth;


        public override event EventHandler<DataEventArgs<GPUPointCloud>> OutputReady;
        public override event EventHandler HotInitialized;
        public override event EventHandler HasFinished;

        protected bool[] colorIsHotInitComplete;

        protected bool[] colorSourcesFinished;

        protected bool fusionDone;

        //A cube whose faces will be used to dimension the orthoPosColMap. Should be the bounding box
        public GameObject Box;
        //Each relevant corner of the cube corresponds to the relevant corners of the ortho images.
        protected Vector4 Origin;
        protected Vector4 Xcorner;
        protected Vector4 Ycorner;
        protected Vector4 Zcorner;
        //Vector4 BoundingBoxPivot;

        public float depthThreshold_Z_meter;

        //4x4Matrix of the boundingbox
        protected Matrix4x4 bBoxMatrix;

        //GameObject in charge of display. The object will follow the cube front face position and orientation
        public GameObject fusionDisplay;
        //Compute shader parameters
        protected int threadGroupsX;
        protected int threadGroupsY;
        protected int threadGroupsZ = 1;
        protected int kernelIndex;
        //camera: point of view where the iso fusion needs to be rendered.

        public Camera cam;
        [Tooltip("Should be 0")]
        public float scalarAngleLimit;
        //public float dampingPower = 2;
        public bool flipNormalsComparator;
        public int thickness;
        //public bool voxelize; //useless for the moment => would lead us to generate our own perfect XY table and take into account the size of the cube. 
        // voxelise if useful for export purpose only but would need our own XYtable and the size of the cube. 
        public bool occludeOppositeCameras;
        protected bool allCamsToFuse;
        protected bool usePairBuffer;
        protected Matrix4x4[] alignmentMatrices;
        [Tooltip("Only for preparation for perspective fusion. Too costly for mobile devices.")]
        public bool TaaActivated;
        public int TaaDelay;
        public float TaaDepthThreshold = 0.5f;
        public int TaaThickness = 5;
        protected int TaaCurrentDelay;
        public bool TaaVisualize;
        [Tooltip("between 0 and 1, 0 everymotion detected, 1 no motion detected, if you know the character doesn't move much put it to 0.9 or 1, low values -0.1 - 0.5- for scenes with a lot of motion")]
        public float motionThreshold;
        public bool motionVisualize;

        protected Queue<GPUPointCloud> frameBuffer = new();

        protected RenderTexture positionHistory;
        protected RenderTexture colorHistory;
        protected int kernelIndex2;
        [Tooltip("TemporalNoiseRemoverCompute is the choice")]
        public ComputeShader TemporalNoiseRemoverCompute;
        protected bool historyCleared;

        protected int threadGroupsX2;
        protected int threadGroupsY2;
        protected int threadGroupsZ2 = 1;

        #region Unity framework Inspector logic
        void OnValidate()
        {
            //By default, we automatically search for those Producers but we can plug any other compatible Producers     
            if (posColMapSources != null)
            {
                for (int i = 0; i < posColMapSources.Length; ++i)
                {
                    if (posColMapSources[i] is not ISourceModule<GPUPointCloud>)
                    {
                        posColMapSources[i] = (Component)posColMapSources[i]?.GetComponents<ISourceModule<GPUPointCloud>>().Last();
                    }
                }
            }
        }

        protected void Start()
        {
            //RGBok = new bool[colorSources.Length]; 
            //DepthOk = new bool[colorSources.Length]; 
            colorIsHotInitComplete = new bool[posColMapSources.Length];

            colorSourcesFinished = new bool[posColMapSources.Length];

            posColMapFrameID = new int[posColMapSources.Length];
            PrepareAdaptativeProjection();


            //Do the Events connections in Start as the GameObjects need to exist
            Connect();
        }

        protected override void OnDestroy()
        {
            base.OnDestroy();
            Disconnect();
        }
        #endregion

        protected void Connect()
        {
            foreach (var colorSource in posColMapSources)
            {
                ((ISourceModule<GPUPointCloud>)colorSource).OutputReady += ColorsRGBReady;
                ((ISourceModule<GPUPointCloud>)colorSource).HotInitialized += OnHotInitFromSource;
                ((ISourceModule<GPUPointCloud>)colorSource).HasFinished += OnHasFinishedFromSource;

            }
        }

        protected void Disconnect()
        {
            foreach (var colorSource in posColMapSources)
            {
                ((ISourceModule<GPUPointCloud>)colorSource).OutputReady -= ColorsRGBReady;
                ((ISourceModule<GPUPointCloud>)colorSource).HotInitialized -= OnHotInitFromSource;
                ((ISourceModule<GPUPointCloud>)colorSource).HasFinished -= OnHasFinishedFromSource;

            }
        }

        void OnHotInitFromSource(object sender, EventArgs e)
        {
            //Debug.Log("OnHotInitFromSource in MULTICOMBINATOR " + this.GetType().Name + " (" + this.name + ")");
            IsHotInitComplete = false;
            for (int i = 0; i < colorIsHotInitComplete.Length; ++i)
            {
                colorIsHotInitComplete[i] = false;

                colorSourcesFinished[i] = false;

            }
        }

        void OnHasFinishedFromSource(object sender, EventArgs e)
        {
            int indexColor = Array.IndexOf(posColMapSources, sender);

            if (indexColor != -1) { colorSourcesFinished[indexColor] = true; }

            if (AllTrue(colorSourcesFinished))
            {
                FinishProcess();
                HasFinished?.Invoke(this, EventArgs.Empty);
                for (int i = 0; i < posColMapSources.Length; ++i)
                {
                    colorSourcesFinished[i] = false;
                }
            }
        }

        bool AllTrue(bool[] _boolArray)
        {
            bool retvalue = true;
            foreach (bool value in _boolArray)
            { retvalue &= value; }
            return retvalue;
        }

        public override void FinishProcess()
        {
            Debug.Log("SPECIAL --- FinishProcess in " + this.GetType().Name);
        }

        protected void InitByColor(int streamIndex, GPUPointCloud gPUPointCloud, FrameInfo frameInfo)
        {
            if (alignmentMatrices == null)
            {
                alignmentMatrices = new Matrix4x4[posColMapSources.Length];
            }
            alignmentMatrices[streamIndex] = gPUPointCloud.appliedMatrix;
            //Debug.Log($"matrix for {streamIndex} is {gPUPointCloud.appliedMatrix}");
            containerRes.width = gPUPointCloud.positionMap.width;
            containerRes.height = gPUPointCloud.positionMap.height;



            colorIsHotInitComplete[streamIndex] = true;
            try
            {
                if (ContextManager.instance == null) { ContextManager.TryFindInstance(); }
                var ctxt = ContextManager.instance?.currentContext;
                if (ctxt != null)
                {
                    if (ctxt.FusionConfig == null)
                    {
                        ctxt.FusionConfig = new();
                    }
                    ctxt.FusionConfig.exportType = ExportType.PerspectiveProjected;
                    if (ctxt.FusionConfig.virtualCamConfigs == null)
                    {
                        ctxt.FusionConfig.virtualCamConfigs = new();
                    }
                    var foundConfig = ctxt.FusionConfig.virtualCamConfigs.Where(c => c.UserAssignedCameraIndex == frameInfo.cameraIndex).FirstOrDefault();
                    if (foundConfig == null/* && Helper.GetCamIndex(gameObject) == Helper.GetCamIndex(cam.gameObject)*/)
                    {
                        ctxt.FusionConfig.virtualCamConfigs.Add(ctxt.CamConfig(frameInfo.cameraIndex).Copy());
                        foundConfig = ctxt.FusionConfig.virtualCamConfigs.Last();
                    }
                    foundConfig.alignmentMatrix = Matrix4x4.TRS(Origin, Box.transform.rotation, Vector3.one);
                    foundConfig.alignmentMatrixPath = Path.Combine(ctxt.Sequence, "alignMatrix_" + frameInfo.cameraIndex + ".json");
                    foundConfig.screenCameraDistance = Box.transform.localPosition.z;
                    foundConfig.projectonScreenWidth = Box.transform.localScale.x;
                    foundConfig.projectonScreenHeight = Box.transform.localScale.y;
                }
            }
            catch (Exception ex)
            {
                Debug.LogWarning("In case you are trying to export a perspective fusion, for the creation of the metadata file a Context manager is needed. Otherwise you can ignore this warning");
            }
            if (colorIsHotInitComplete.All(x => x)) HotInit();
        }

        public override void HotInit()
        {

            //Debug.Log("HotInit in MULTICOMBINATOR " + this.GetType().Name + " (" + this.name + ")");
            TaaCurrentDelay = TaaDelay;

            PrepareOutPositionBuffer();
            PrepareOutColorBuffer();
            PrepareDepthMap();

            PreparePositionTextureArray();
            PrepareColorTextureArray();

            PrepareComputeShader();

            AddAllCamstoFusion();

            //base.HotInit();
            IsHotInitComplete = true;
            HotInitialized?.Invoke(this, EventArgs.Empty);
        }

        protected void AddAllCamstoFusion()
        {
            //Give to posColMapToFuse list the full list of the posColMapSources array
            posColMapToFuse.Clear();
            for (int i = 0; i < posColMapSources.Length; ++i)
            {
                posColMapToFuse.Add(posColMapSources[i]);
            }
            allCamsToFuse = true;
        }

        ///<summary>Creates or recreates the Texture2D, sets some parameters and gives to tba the byte[] representing the raw texture data


        protected void PrepareOutPositionBuffer()
        {
            positionsOut1 = new RenderTexture(finalWidth, finalHeight, 0, RenderTextureFormat.ARGBFloat)
            {
                enableRandomWrite = true,
                useMipMap = false,
                filterMode = FilterMode.Point,
                name = "perspPosOut1"
            };
            positionsOut1.Create();
            positionsOut2 = new RenderTexture(finalWidth, finalHeight, 0, RenderTextureFormat.ARGBFloat)
            {
                enableRandomWrite = true,
                useMipMap = false,
                filterMode = FilterMode.Point,
                name = "perspPosOut2"
            };
            positionsOut2.Create();
        }

        protected void PrepareOutColorBuffer()
        {
            colorsOut1 = new RenderTexture(finalWidth, finalHeight, 0, RenderTextureFormat.ARGB32) //ARGBFloat cos BGRA32 comes with a gamma
            {
                graphicsFormat = UnityEngine.Experimental.Rendering.GraphicsFormat.R8G8B8A8_UNorm,
                enableRandomWrite = true,
                useMipMap = false,
                filterMode = FilterMode.Point,
                name = "perspColOut1"
            };
            colorsOut1.Create();
            colorsOut2 = new RenderTexture(finalWidth, finalHeight, 0, RenderTextureFormat.ARGB32) //ARGBFloat cos BGRA32 comes with a gamma
            {
                graphicsFormat = UnityEngine.Experimental.Rendering.GraphicsFormat.R8G8B8A8_UNorm,
                enableRandomWrite = true,
                useMipMap = false,
                filterMode = FilterMode.Point,
                name = "perspColOut2"
            };
            colorsOut2.Create();
        }
        protected void PrepareDepthMap()
        {
            depthMap = new RenderTexture(finalWidth, finalHeight, 0, RenderTextureFormat.RInt);
            depthMap.enableRandomWrite = true;
            depthMap.Create();
        }
        protected void PreparePositionTextureArray()
        {
            positionHistory = new RenderTexture(finalWidth, finalHeight, 0)
            {
                format = positionsOut1.format,
                graphicsFormat = positionsOut1.graphicsFormat,
                dimension = UnityEngine.Rendering.TextureDimension.Tex2DArray,
                volumeDepth = TaaDelay * 2 + 1,
                enableRandomWrite = true,
                useMipMap = false,
                name = "historyDepthArray"
            };
            positionHistory.Create();
        }
        protected void PrepareColorTextureArray()
        {
            colorHistory = new RenderTexture(finalWidth, finalHeight, 0)
            {
                format = colorsOut1.format,
                graphicsFormat = colorsOut1.graphicsFormat,
                dimension = UnityEngine.Rendering.TextureDimension.Tex2DArray,
                volumeDepth = TaaDelay * 2 + 1,
                enableRandomWrite = true,
                useMipMap = false,
                name = "historyColorArray"
            };
            colorHistory.Create();
        }


        protected class ID
        {
            public static int DepthMap = Shader.PropertyToID("DepthMap");
            public static int PosMapOut = Shader.PropertyToID("PosMapOut");
            public static int PosMapRead = Shader.PropertyToID("PosMapRead");
            public static int ColMapOut = Shader.PropertyToID("ColMapOut");
            public static int ColMapRead = Shader.PropertyToID("ColMapRead");
            public static int O = Shader.PropertyToID("O");
            public static int X = Shader.PropertyToID("X");
            public static int Y = Shader.PropertyToID("Y");
            public static int Z = Shader.PropertyToID("Z");
            //public static int bBoxPivot = Shader.PropertyToID("bBoxPivot");
            public static int orthoWidth = Shader.PropertyToID("orthoWidth");
            public static int orthoHeight = Shader.PropertyToID("orthoHeight");
            public static int orthoDepth = Shader.PropertyToID("orthoDepth");
            //public static int startNewFusion = Shader.PropertyToID("startNewFusion"); //useless now
            public static int bBoxMat = Shader.PropertyToID("bBoxMat");
            public static int depthThrsld = Shader.PropertyToID("depthThrsld");
            public static int scalarNormalLimit = Shader.PropertyToID("scalarNormalLimit");
            public static int voxelized = Shader.PropertyToID("voxelized");
            public static int camPos = Shader.PropertyToID("camPos");
            public static int FlipNormalsComparator = Shader.PropertyToID("FlipNormalsComparator");
            public static int Fusion = Shader.PropertyToID("Fusion");
            //public static int DebugPixelWidth = Shader.PropertyToID("DebugPixelWidth");
            //public static int DebugPixelHeight = Shader.PropertyToID("DebugPixelHeight");
            public static int Thickness = Shader.PropertyToID("Thickness");

            //ID of the TAA properties
            public static int TaaThickness = Shader.PropertyToID("thickness");
            public static int TaaDelay = Shader.PropertyToID("Delay");
            public static int TaaDepthThreshold = Shader.PropertyToID("depthThreshold");
            public static int TaaVisualize = Shader.PropertyToID("visualize");
            public static int PositionHistory = Shader.PropertyToID("PositionHistory");
            public static int ColorHistory = Shader.PropertyToID("ColorHistory");

            public static int motionThreshold = Shader.PropertyToID("motionThreshold");
            public static int motionVisualize = Shader.PropertyToID("motionVisualize");
        }
        protected void PrepareComputeShader()
        {


            PerspFusionCompute = Instantiate(PerspFusionCompute); //If we don't instantiate, the same CS is used by several modules. Intéressant
            kernelIndex = PerspFusionCompute.FindKernel("CSMain");
            threadGroupsX = Mathf.CeilToInt(containerRes.width / 8);
            threadGroupsY = Mathf.CeilToInt(containerRes.height / 8);

            if (TemporalNoiseRemoverCompute != null)
            {
                TemporalNoiseRemoverCompute = Instantiate(TemporalNoiseRemoverCompute);
                kernelIndex2 = TemporalNoiseRemoverCompute.FindKernel("CSMain");
            }

            threadGroupsX2 = Mathf.CeilToInt(finalWidth / 8);
            threadGroupsY2 = Mathf.CeilToInt(finalHeight / 8);

            //OrthoFusionCompute.SetTexture(kernelIndex, ID.ColMapOut, colorsOut);
            //OrthoFusionCompute.SetTexture(kernelIndex, ID.PosMapOut, positionsOut);

            //Debug.Log("X distance : " + (Xcorner.x - Origin.x));

            //Debug.Log("Y distance : " + (Ycorner.y - Origin.y));
            //fusionDisplay.transform.position = Box.transform.TransformPoint(new Vector4(Box.GetComponent<MeshFilter>().mesh.vertices[7].x, Box.GetComponent<MeshFilter>().mesh.vertices[7].y, Box.GetComponent<MeshFilter>().mesh.vertices[7].z));
        }

        protected void PrepareAdaptativeProjection()
        {
            //Vector3[] vertices = new Vector3[24];

            /*for(int i = 0; i < vertices.Length; i++) 
            {
                vertices[i] = Box.GetComponent<MeshFilter>().mesh.vertices[i];
            }

            Box.GetComponent<MeshFilter>().mesh.vertices = vertices;

            Box.GetComponent<MeshFilter>().mesh.RecalculateBounds();*/

            //cf le schéma de la création d'un cube dans Unity 24 vertex : https://forum.unity.com/threads/cube-mesh-order-of-vertices-and-triangles.873901/ 

            //Front face of the cube
            Origin = Box.transform.TransformPoint(new Vector4(Box.GetComponent<MeshFilter>().mesh.vertices[7].x, Box.GetComponent<MeshFilter>().mesh.vertices[7].y, Box.GetComponent<MeshFilter>().mesh.vertices[7].z, 0));
            Xcorner = Box.transform.TransformPoint(new Vector4(Box.GetComponent<MeshFilter>().mesh.vertices[6].x, Box.GetComponent<MeshFilter>().mesh.vertices[6].y, Box.GetComponent<MeshFilter>().mesh.vertices[6].z, 0));
            Ycorner = Box.transform.TransformPoint(new Vector4(Box.GetComponent<MeshFilter>().mesh.vertices[5].x, Box.GetComponent<MeshFilter>().mesh.vertices[5].y, Box.GetComponent<MeshFilter>().mesh.vertices[5].z, 0));
            Zcorner = Box.transform.TransformPoint(new Vector4(Box.GetComponent<MeshFilter>().mesh.vertices[14].x, Box.GetComponent<MeshFilter>().mesh.vertices[14].y, Box.GetComponent<MeshFilter>().mesh.vertices[14].z, 0));
            //Bounding Box pivot
            //BoundingBoxPivot = Box.transform.position;

            /*Debug.Log("Origin : " + Origin);
            Debug.Log("Xcorner : " + Xcorner);
            Debug.Log("Ycorner : " + Ycorner);
            Debug.Log("Zcorner : " + Zcorner);
            Debug.Log("Bounding Box Pivot : "+ BoundingBoxPivot);*/

            //Get the world 4X4Matrix of the bounding box 
            //Take care of local and world values
            Vector3 boxScale = new Vector3(Box.transform.localScale.x, Box.transform.localScale.y, Box.transform.localScale.z); // not used 
            // Adjust box scale so it fits the camera FOV X and Y 
            //Box.transform.localScale = new Vector3(cam., 0.1f, Box.transform.localScale.z);
            //Damping function : Scaling the box to compensate the size decreasing of the image when getting closer to the box center : box scale = 1 - 1/(distance + 1)^n // not perfect but compensate well
            //Box.transform.localScale = new Vector3(1 - 1 / (Mathf.Pow((Vector3.Distance(cam.transform.position, Box.transform.position)+1), dampingPower)), 1 - 1 / (Mathf.Pow((Vector3.Distance(cam.transform.position, Box.transform.position)+1), dampingPower)), 1 - 1 / (Mathf.Pow((Vector3.Distance(cam.transform.position, Box.transform.position)+1), dampingPower)));

            //Distance constante entre la caméra et la face du cube mais pas fluide
            //Box.transform.localScale = new Vector3(0.1f, 0.1f,Vector3.Distance(cam.transform.position, Box.transform.position)*2-0.5f);//(Mathf.Pow(Vector3.Distance(cam.transform.position, Box.transform.position), 2)
            //Matrix4x4 scaleMatrix = Matrix4x4.Scale(boxScale);
            Vector3 boxPosition = Box.transform.TransformPoint(new Vector3(Box.transform.localPosition.x, Box.transform.localPosition.y, Box.transform.localPosition.z));
            Matrix4x4 translateMatrix = Matrix4x4.Translate(boxPosition);
            Quaternion boxRotation = Box.transform.rotation;
            Matrix4x4 rotateMatrix = Matrix4x4.Rotate(Quaternion.Inverse(boxRotation));
            //Matrix4x4 rotateMatrix = Matrix4x4.Rotate(boxRotation);
            //bBoxMatrix = translateMatrix * Box.transform.localToWorldMatrix;
            bBoxMatrix = rotateMatrix * Matrix4x4.identity;
            //bBoxMatrix = Matrix4x4.identity;

            //Apply cube orientation and Origin position to the GameObject Displaying the Fusion

            //TEST sans contrecarrer la rotation et la position avec la transformation de l afficheur !!!
            if (fusionDisplay != null)
            {
                fusionDisplay.transform.localRotation = boxRotation;
                fusionDisplay.transform.localPosition = new Vector3(Origin.x, Origin.y, Origin.z);
            }
            //fusionDisplay.transform.position = BoundingBoxPivot;

            //Rotate the bounding box according to the camera
            //Box.transform.rotation = Quaternion.LookRotation(Box.transform.position - cam.transform.position);



        }
        protected void PreparePosColMapToFuse() //V1.1
        {
            //A mettre dans une fonction séparée. Attention ! Doit se faire une fois par cycle de fusion pas par rajout de frame dans la fusion 
            //Debug.Log("Camera vector : " + (Vector3.Normalize(Box.transform.position - cam.transform.position)).ToString());
            posColMapToFuse.Clear();
            for (int i = 0; i < posColMapSources.Length; ++i)
            {
                Vector3 forward = alignmentMatrices[i] * Vector3.forward;

                if (Vector3.Dot(Vector3.Normalize(Box.transform.position - cam.transform.position), forward) > 0)
                {
                    posColMapToFuse.Add(posColMapSources[i]);
                }
            }
            //Debug.Log("posColoMapToFuse size : " + posColMapToFuse.Count);
            //posColMapSources = new Component[posColMapToFuse.Count];

            /*for (int i = 0; i < posColMapToFuse.Count; ++i)
            {
                posColMapSources[i] = posColMapToFuse[i];
            }*/
        }
        protected void ColorsRGBReady(object sender, DataEventArgs<GPUPointCloud> e)
        {

            //Debug.Log("frameId:" + e.FrameID);
            if (e.Output.positionMap != null && e.Output.colorMap != null)
            {
                //int index = posColMapToFuse.IndexOf((Component) sender);
                int index = Array.IndexOf(posColMapSources, sender);

                if (!colorIsHotInitComplete[index])
                {
                    InitByColor(index, e.Output, e.FrameInfo);
                }
                else if (IsHotInitComplete)
                {

                    //Ortho Fusion for each posColMapSource

                    //Debug.Log("posColMapSources Length : "+posColMapSources.Length);

                    //V1.1 : if posColMapSources arriving belongs to the posColMapToFuse List, we autorize the fusion, 
                    //Debug.Log($"Before testeing if contains : {index} {e.FrameID}");

                    if (posColMapToFuse.Contains(posColMapSources[index])) PerspFusionDataProcess(e.Output);


                    /*for (int i = 0; i < posColMapToFuse.Count; i++)
                    {
                        if (posColMapSources[index] == posColMapToFuse[i]) IsoFusionDataProcess(e.Output.Item1, e.Output.Item2);
                    }*/


                    //CopyColorIntoTexture(e.Output, index, posColMapSources.Length);
                    //Debug.Log("e.FrameID : " + e.FrameID);

                    //Debug.Log("index : " + Helper.GetCamIndex(((Component)sender).gameObject) + ", e.FrameID : " + e.FrameInfo.frameID);

                    posColMapFrameID[index] = e.FrameInfo.frameID;

                    if (posColMapFrameID.All(x => x == e.FrameInfo.frameID))
                    {
                        for (int i = 0; i < posColMapSources.Length; ++i)
                        {
                            posColMapFrameID[i] = -1;
                        }
                        //Debug.Log($"ColorReady for {e.FrameID}");
                        var gpuPointCloud = new GPUPointCloud();
                        if (usePairBuffer)
                        {
                            gpuPointCloud.positionMap = positionsOut2;
                            gpuPointCloud.colorMap = colorsOut2;
                        }
                        else
                        {
                            gpuPointCloud.positionMap = positionsOut1;
                            gpuPointCloud.colorMap = colorsOut1;
                        }
                        gpuPointCloud.appliedMatrix = Matrix4x4.TRS(Origin, Box.transform.rotation, Vector3.one);
                        OutputReady?.Invoke(this, new(gpuPointCloud, e.FrameInfo));
                        fusionDone = true;
                        usePairBuffer = !usePairBuffer;
                    }

                }
            }
        }

        protected virtual void PerspFusionDataProcess(GPUPointCloud PCin)
        {

            RenderTexture colorsOut, positionsOut;

            if (!usePairBuffer)
            {
                colorsOut = colorsOut1;
                positionsOut = positionsOut1;
            }
            else
            {
                colorsOut = colorsOut2;
                positionsOut = positionsOut2;
            }
            //Debug.Log("Fusion Done ? : " + fusionDone);
            if (fusionDone)//||fusion==false
            {
                //Graphics.SetRenderTarget(colorsOut);
                //Clear the out Rendertextures Buffers at each initialization of a new fusion
                RenderTexture.active = colorsOut;
                GL.Clear(true, true, Color.clear);
                RenderTexture.active = positionsOut;
                GL.Clear(true, true, Color.clear);
                RenderTexture.active = depthMap;
                GL.Clear(true, true, Color.clear);

                //Once by fusion cycle prepare the array of component to be fused. Only the kinects in the same axis than the main camera are fused.
                if (occludeOppositeCameras)
                {
                    PreparePosColMapToFuse();
                    allCamsToFuse = false;
                }
                else if (!occludeOppositeCameras && !allCamsToFuse)
                {
                    AddAllCamstoFusion();
                    allCamsToFuse = true;
                }
            }


            //Fusion parameters
            PerspFusionCompute.SetTexture(kernelIndex, ID.ColMapOut, colorsOut);
            PerspFusionCompute.SetTexture(kernelIndex, ID.PosMapOut, positionsOut);
            PerspFusionCompute.SetTexture(kernelIndex, ID.DepthMap, depthMap);
            //OrthoFusionCompute.SetBool(ID.startNewFusion, fusionDone);
            //PerspFusionCompute.SetBool(ID.voxelized, voxelize);
            PrepareAdaptativeProjection();
            PerspFusionCompute.SetVector(ID.O, Origin);
            PerspFusionCompute.SetVector(ID.X, Xcorner);
            PerspFusionCompute.SetVector(ID.Y, Ycorner);
            PerspFusionCompute.SetVector(ID.Z, Zcorner);
            //PerspFusionCompute.SetVector(ID.bBoxPivot, BoundingBoxPivot);

            // send the world position of the cam in the vector 4
            //Debug.Log("camera position : " + cam.transform.TransformPoint(new Vector4(cam.transform.localPosition.x, cam.transform.localPosition.y, cam.transform.localPosition.z, 0)));

            //PerspFusionCompute.SetVector(ID.camPos, cam.transform.TransformPoint(new Vector4(cam.transform.localPosition.x, cam.transform.localPosition.y, cam.transform.localPosition.z, 0)));
            //Debug.Log("camera position : " + new Vector4(cam.transform.position.x, cam.transform.position.y, cam.transform.position.z, 0));
            PerspFusionCompute.SetVector(ID.camPos, new Vector4(cam.transform.position.x, cam.transform.position.y, cam.transform.position.z, 0));

            PerspFusionCompute.SetInt(ID.orthoWidth, finalWidth);
            PerspFusionCompute.SetInt(ID.orthoHeight, finalHeight);
            PerspFusionCompute.SetInt(ID.orthoDepth, finalDepth);
            PerspFusionCompute.SetFloat(ID.depthThrsld, depthThreshold_Z_meter);
            PerspFusionCompute.SetInt(ID.Thickness, thickness);
            PerspFusionCompute.SetFloat(ID.scalarNormalLimit, scalarAngleLimit);
            PerspFusionCompute.SetMatrix(ID.bBoxMat, bBoxMatrix);
            PerspFusionCompute.SetBool(ID.FlipNormalsComparator, flipNormalsComparator);
            PerspFusionCompute.SetBool(ID.Fusion, fusion);
            //PerspFusionCompute.SetInt(ID.DebugPixelWidth, debugPixelWidth);
            //PerspFusionCompute.SetInt(ID.DebugPixelHeight, debugPixelHeight);

            // Add current frame to buffer and remove oldest if necessary
            //frameBuffer.Enqueue(new GPUPointCloud(PCin));
            //if (frameBuffer.Count > maxFrameHistory)
            //{
            //    var oldFrame = frameBuffer.Dequeue();
            //    oldFrame.Dispose();
            //}

            //int frameIndex = 0;
            //foreach (var frame in frameBuffer)
            //{
            // 
            //    {
            //        PerspFusionCompute.SetTexture(kernelIndex, ID.PosMapRead, frame.positionMap);

            //        PerspFusionCompute.SetTexture(kernelIndex, ID.ColMapRead, frame.colorMap);

            //        PerspFusionCompute.Dispatch(kernelIndex, threadGroupsX, threadGroupsY, threadGroupsZ);
            //    }

            //    frameIndex++;
            //}

            if (TaaActivated)
            {
                if (historyCleared) historyCleared = false;
                //TAA parameters
                TemporalNoiseRemoverCompute.SetInt(ID.TaaDelay, TaaDelay);
                TemporalNoiseRemoverCompute.SetInt(ID.TaaThickness, TaaThickness);
                TemporalNoiseRemoverCompute.SetFloat(ID.TaaDepthThreshold, TaaDepthThreshold);
                TemporalNoiseRemoverCompute.SetBool(ID.TaaVisualize, TaaVisualize);

                TemporalNoiseRemoverCompute.SetFloat(ID.motionThreshold, motionThreshold);
                TemporalNoiseRemoverCompute.SetBool(ID.motionVisualize, motionVisualize);

                if (TaaCurrentDelay != TaaDelay) HotInit();

                // Add current frame to buffer and remove oldest if necessary
                frameBuffer.Enqueue(new GPUPointCloud(PCin));

                while (frameBuffer.Count > TaaDelay * 2 + 1)
                {
                    var oldFrame = frameBuffer.Dequeue();
                    oldFrame.Dispose();
                }

                // Set previous frames in the compute shader

                int frameIndex = 0;
                foreach (var frame in frameBuffer)
                {

                    //PosMap Read
                    PerspFusionCompute.SetTexture(kernelIndex, ID.PosMapRead, frame.positionMap);
                    //ColMap Read
                    PerspFusionCompute.SetTexture(kernelIndex, ID.ColMapRead, frame.colorMap);

                    PerspFusionCompute.Dispatch(kernelIndex, threadGroupsX, threadGroupsY, threadGroupsZ);

                    Graphics.CopyTexture(positionsOut, 0, 0, positionHistory, frameIndex, 0);
                    Graphics.CopyTexture(colorsOut, 0, 0, colorHistory, frameIndex, 0);

                    RenderTexture.active = colorsOut;
                    GL.Clear(true, true, Color.clear);
                    RenderTexture.active = positionsOut;
                    GL.Clear(true, true, Color.clear);
                    RenderTexture.active = depthMap;
                    GL.Clear(true, true, Color.clear);



                    frameIndex++;

                }
                //Test de vizualisation de la frame Delay après traitement par la persp fusion
                //Graphics.CopyTexture(positionHistory, TaaDelay, 0,positionsOut, 0, 0);
                //Graphics.CopyTexture(colorHistory, TaaDelay, 0,colorsOut, 0, 0);

                TemporalNoiseRemoverCompute.SetTexture(kernelIndex2, ID.ColMapOut, colorsOut);
                TemporalNoiseRemoverCompute.SetTexture(kernelIndex2, ID.PosMapOut, positionsOut);

                TemporalNoiseRemoverCompute.SetTexture(kernelIndex2, ID.PositionHistory, positionHistory);
                TemporalNoiseRemoverCompute.SetTexture(kernelIndex2, ID.ColorHistory, colorHistory);
                TemporalNoiseRemoverCompute.Dispatch(kernelIndex2, threadGroupsX2, threadGroupsY2, threadGroupsZ2);
            }
            else
            {
                if (!historyCleared)
                {
                    frameBuffer.Clear();
                    RenderTexture.active = positionHistory;
                    GL.Clear(true, true, Color.clear);
                    RenderTexture.active = colorHistory;
                    GL.Clear(true, true, Color.clear);
                    historyCleared = true;
                }

                PerspFusionCompute.SetTexture(kernelIndex, ID.PosMapRead, PCin.positionMap);

                PerspFusionCompute.SetTexture(kernelIndex, ID.ColMapRead, PCin.colorMap);
                PerspFusionCompute.Dispatch(kernelIndex, threadGroupsX, threadGroupsY, threadGroupsZ);




            }
            if (fusionDone) fusionDone = false;
        }


        public override void CleanUp()
        {
            Destroy(positionsOut1);
            Destroy(colorsOut1);
            Destroy(positionsOut2);
            Destroy(colorsOut2);
            Destroy(colorHistory);
            Destroy(positionHistory);
            Destroy(depthMap);
            foreach (var frame in frameBuffer)
                frame.Dispose();
            frameBuffer.Clear();
        }
    }
}