#pragma kernel CSMain

RWTexture2D<float4> PosMapOut; 
RWTexture2D<float4> ColMapOut; 

Texture2D<float4> PosMapRead;
Texture2D<float4> ColMapRead; 

float depththrshld; //edge filter depth
uint topthick; //top edge thickeness
uint rightthick; //right edge thickness
uint bottomthick;
uint leftthick; 
bool visualize;



[numthreads(8,8,1)]
void CSMain (uint2 id : SV_DispatchThreadID)
{
    //float4 col = ColMapRead.Load(int3(id.xy, 0)); to keep in mind
    
    //DEBUG
    //ColMapOut[id] = float4(1, ColMapRead[id].gb, 1);
    PosMapOut[id] = PosMapRead[id];
    
    //New method Android compatible // IMPORTANT for android we cannot read and write on the same RWtexture2D but we can read it in a condition or a loop
    
    ColMapOut[id] = ColMapRead[id];
    if (visualize)
    {
        if (abs(PosMapRead[uint2(id.x, id.y)].z - PosMapRead[uint2(id.x + topthick, id.y)].z) > depththrshld)
        {
            
            ColMapOut[id] = float4(1, 0, 0, 1);
        
        }
    
        if (abs(PosMapRead[uint2(id.x, id.y)].z - PosMapRead[uint2(id.x, id.y - rightthick)].z) > depththrshld)
        {
            
            ColMapOut[id] = float4(1, 0, 0, 1);
        
        }
    
        if (abs(PosMapRead[uint2(id.x, id.y)].z - PosMapRead[uint2(id.x - bottomthick, id.y)].z) > depththrshld)
        {
            
            ColMapOut[id] = float4(1, 0, 0, 1);
        
        }
    
        if (abs(PosMapRead[uint2(id.x, id.y)].z - PosMapRead[uint2(id.x, id.y + leftthick)].z) > depththrshld)
        {
            
            ColMapOut[id] = float4(1, 0, 0, 1);
        
        }
    }
    else
    {
        if (abs(PosMapRead[uint2(id.x, id.y)].z - PosMapRead[uint2(id.x + topthick, id.y)].z) > depththrshld)
        {
            PosMapOut[id] = float4(PosMapRead[id].x, PosMapRead[id].y, PosMapRead[id].z, 0);
        }
        else if (abs(PosMapRead[uint2(id.x, id.y)].z - PosMapRead[uint2(id.x, id.y - rightthick)].z) > depththrshld)
        {

            PosMapOut[id] = float4(PosMapRead[id].x, PosMapRead[id].y, PosMapRead[id].z, 0);
        }
        else if (abs(PosMapRead[uint2(id.x, id.y)].z - PosMapRead[uint2(id.x - bottomthick, id.y)].z) > depththrshld)
        {
            PosMapOut[id] = float4(PosMapRead[id].x, PosMapRead[id].y, PosMapRead[id].z, 0);
        }
        else if (abs(PosMapRead[uint2(id.x, id.y)].z - PosMapRead[uint2(id.x, id.y + leftthick)].z) > depththrshld)
        {
            PosMapOut[id] = float4(PosMapRead[id].x, PosMapRead[id].y, PosMapRead[id].z, 0);
        }
        else
            PosMapOut[id] = PosMapRead[id];
    }
    //ColMapIn[id] = float4(1, 0, 0, 1); DEBUG
    
    //ColMapIn[id] = (abs(PosMapRead[uint2(id.x, id.y)].z - PosMapRead[uint2(id.x + topthick, id.y)].z) > depththrshld) ? float4(1, 0, 0, 1) : ColMapIn[id]; //interessant mais les variables ne passent pas
    
    //old method
    
    /*for (int k = 0; k < topthick; k++)
    {
        if (abs(PosMapRead[uint2(id.x, id.y)].z - PosMapRead[uint2(id.x + k, id.y)].z) > depththrshld)
        {
            //ColMapIn[id] = float4(1, 0, 0, 1);
            PosMapRead[id] = float4(PosMapRead[id].x, PosMapRead[id].y, PosMapRead[id].z, 0);

        }
    }
    for (int i = 0; i < bottomthick; i++)
    {
        if (abs(PosMapRead[uint2(id.x, id.y)].z - PosMapRead[uint2(id.x - i, id.y)].z) > depththrshld)
        { 
            //ColMapIn[id] = float4(1, 0, 0, 1);    
            PosMapRead[id] = float4(PosMapRead[id].x, PosMapRead[id].y, PosMapRead[id].z, 0);
        }
    }*/
    
    /*for (int j = 0; j < rightthick; j++)
    {
        if (abs(PosMapRead[uint2(id.x, id.y)].z - PosMapRead[uint2(id.x, id.y-j)].z) > depththrshld)
        {
            ColMapIn[id] = float4(1, 0, 0, 1);
            //PosMapRead[id] = float4(PosMapRead[id].x, PosMapRead[id].y, PosMapRead[id].z, 0);
            //ColMapIn[id] = float4(ColMapIn[id].x, ColMapIn[id].y, ColMapIn[id].z, 0);
        }
    }*/
    
    
    /*for (int l = 0; l < leftthick; l++)
    {
        if (abs(PosMapRead[uint2(id.x, id.y)].z - PosMapRead[uint2(id.x, id.y + l)].z) > depththrshld)
        {
            //ColMapIn[id] = float4(1, 0, 0, 1);
            PosMapRead[id] = float4(PosMapRead[id].x, PosMapRead[id].y, PosMapRead[id].z, 0);
        }
    }*/
  
}